pipeline:
  name: new
  identifier: Build_abdulmoizz44_Cartoon_animation_web_1761671825946
  projectIdentifier: cartoon
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
              - step:
                  type: BuildAndPushECR
                  name: BuildAndPushECR_1
                  identifier: BuildAndPushECR_1
                  spec:
                    connectorRef: awsconnector
                    region: us-east-1
                    account: "084828598848"
                    imageName: 084828598848.dkr.ecr.us-east-1.amazonaws.com/cartoon
                    tags: <+input>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Ssh
          service:
            serviceRef: cartoonservice
          environment:
            environmentRef: staging
            deployToAll: false
            infrastructureDefinitions:
              - identifier: secureshell
          execution:
            steps:
              - step:
                  name: Deploy
                  identifier: Deploy
                  timeout: 10m
                  strategy:
                    repeat:
                      items: <+stage.output.hosts>
                  template:
                    templateRef: account.Default_Install_War_Bash
                    templateInputs:
                      type: Command
                      spec:
                        environmentVariables:
                          - name: DestinationDirectory
                            type: String
                            value: $HOME/<+service.name>/<+env.name>
            rollbackSteps:
              - step:
                  name: Rollback
                  identifier: Deploy
                  timeout: 10m
                  strategy:
                    repeat:
                      items: <+stage.output.hosts>
                  template:
                    templateRef: account.Default_Install_War_Bash
                    templateInputs:
                      type: Command
                      spec:
                        environmentVariables:
                          - name: DestinationDirectory
                            type: String
                            value: $HOME/<+service.name>/<+env.name>
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: abdulmoizz44/Cartoon-animation-web
        build: <+input>
  tags: {}
