pipeline:
  name: Build Cartoon-animation-web
  identifier: Build_abdulmoizz44_Cartoon_animation_web_1761852407208
  projectIdentifier: k8spractise
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
              - step:
                  type: BuildAndPushECR
                  name: BuildAndPushECR
                  identifier: BuildAndPushECR
                  spec:
                    connectorRef: awsconnector
                    region: us-east-1
                    account: "084828598848"
                    imageName: 084828598848.dkr.ecr.us-east-1.amazonaws.com/cartoon
                    tags: <+input>
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: echo 'Yo build has been pushed'
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: abdulmoizz44/Cartoon-animation-web
        build: <+input>
